services:
  django_backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
      target: dev
    command: sh -c "python manage.py makemigrations api && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    ports:
      - 8000:8000
    volumes:
      - ./Backend/:/app
      
  gateway:
    container_name: gateway
    build:
      context: ./Gateway
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      SECRET_KEY: RxtBeFg7yunnBFGwa8dYa8Q7CiUiTJVn
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_URL: r2dbc:postgresql://database:5432/user_database
      DATABASE_NAME: user_database

      ADMIN_UNAME: student
      ADMIN_PASSWORD: student
    volumes:
      - ./Gateway/:/app

  database:
    container_name: database
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: student
    volumes:
      - ./Database/InitDatabase:/docker-entrypoint-initdb.d
