spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping:
        - true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000,https://lublean.com"
            allowedMethods:
            - GET
            - POST
            - PUT
            - PATCH
            - OPTIONS
            - HEAD
            allowedHeaders: "*"
